title: portfolio
author: wldud01.io
email: yunjiyeong0106@gmail.com
description: >-
  ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks feature.
  This theme provides a set of page-level components and a pre-configured Forestry Blocks UI
  that will empower content editors to construct their own webpages.
baseurl: "/myblog" # the subpath of your site, e.g. /blog
url: "https://wldud01.github.io" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

